### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [jonathanahern/mapMyRat#2]
- [x] Are users rats? 
- [x] Routes - lat, long, etc. can be combined into 1 column -- "google_route" or "path_line" - we can chat about this more on Monday 
- [x] What is response_id on comments table?

**Comment by jonathanahern** [comment]
* It’s a site to map your rat sitings and build rodent tours and burn calories as you go.
* I wasn't sure how google maps stores their data so I just guessed.
* Looking at the site I realize I don't need to have comments reply to each other.
